### ISSUE TITLE
Support casting URL parameters

### ISSUE THREAD

**Issue by sjoerdjob** [sjoerdjob/django-simple-url#1]
There has been discussion of enabling auto-casting of parameters.

Especially for the `<int:param>` fields it should be an easy option to add.

Are there any other casts that should be looked at?

**Comment by sjoerdjob** [comment]
Already supported.

**Comment by EmilStenstrom** [comment]
I'm reading this section as that casting is not supported? https://github.com/sjoerdjob/django-simple-url#caveats

**Comment by sjoerdjob** [comment]
Yes, README is outdated. Going to fix today or tomorrow.

**Comment by sjoerdjob** [comment]
Updated the README from my phone.
