### ISSUE TITLE
Latest released version 0.0.3 on PyPI is older than latest master 0.0.2.

### ISSUE THREAD

**Issue by EmilStenstrom** [sjoerdjob/django-simple-url#4]
Would you mind sending up the latest version to PyPI? I would love to use the str type, but it doesn't work with the 0.0.3 version that's up on PyPI.

Thanks for this great library, you've really nailed it!

**Comment by sjoerdjob** [comment]
I won't get to it before the weekend. Hopefully Monday.

**Comment by sjoerdjob** [comment]
So not Monday, Tuesday it is. On PyPI we now have 0.0.4. Not satisfied about the PKG-INFO that was uploaded though, need to investigate.

**Comment by EmilStenstrom** [comment]
Thanks!
